#!/usr/bin/env python2
from __future__ import print_function
import pika
from sys import argv, exit, stdout
from os import environ
queue = environ.get("CARROT_QUEUE", "alien_jobs")
rmq_host = environ.get("CARROT_RABBITMQ", "localhost:5672")
rmq_port = 5672

def get_queue_size():
  n = 0
  try:
    rmq = pika.BlockingConnection(pika.ConnectionParameters(rmq_host, rmq_port))
    ch = rmq.channel()
    resp = ch.queue_declare(queue=queue, passive=True)
    n = resp.method.message_count
  except:
    pass
  try:
    rmq.close()
  except:
    pass
  return n

if ":" in rmq_host:
  rmq_host,rmq_port = rmq_host.split(":", 1)
  try:
    rmq_port = int(rmq_port)
  except ValueError as e:
    exit(2)
expect = False
if len(argv) == 1:
  # has to return 0 to pass AliEn healthcheck
  exit(0)
for a in argv:
  if expect and (a == "JobStatus==1" or a == "JobStatus==1 || JobStatus==2"):
    # 1 == waiting, 2 == running (which we don't know here)
    for _ in range(get_queue_size()):
      print("W")
    exit(0)
  if a == "-constraint":
    expect = True
  else:
    expect = False
exit(1)
